service: jira-webhooks

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2

  environment:
    JIRA_URL: ${ssm:JIRA_URL}
    JIRA_USERNAME: ${ssm:JIRA_USERNAME}
    JIRA_PASSWORD: ${ssm:JIRA_PASSWORD~true}
    JIRA_BASE_JQL: filter = "TODO visible"
    JIRA_SORT_FIELDS: Importance, Rank

functions:
  updateIssueRanksForSortViaWebhook:
    handler: src/functions/updateIssueRanksForSort.handleViaWebhook
    reservedConcurrency: 1
    events:
      - http: POST updateIssueRanksForSort
  updateIssueRanksForSortDirect:
    handler: src/functions/updateIssueRanksForSort.handleDirect
    events:
      - schedule: cron(5 12 * * ? *)

  handleIssueRecurrence:
    handler: src/functions/recurrence.handleTransitionWebhook
    events:
      - http: POST handleRecurrence
