service: jira-webhooks

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2

  environment:
    JIRA_URL: ${ssm:JIRA_URL}
    JIRA_USERNAME: ${ssm:JIRA_USERNAME}
    JIRA_PASSWORD: ${ssm:JIRA_PASSWORD~true}
    JIRA_BASE_JQL: project = TODO and statusCategory != Done
    JIRA_SORT_FIELDS: Importance, Rank

functions:
  updateIssueRanksForSortViaWebhook:
    handler: src/functions/updateIssueRanksForSort.handleViaWebhook
    events:
      - http: POST update-issue-ranks-for-sort
  updateIssueRanksForSortDirect:
    handler: src/functions/updateIssueRanksForSort.handleDirect
    events:
      - schedule: cron(5 12 * * ? *)
