service: jira-webhooks

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2

  environment:
    JIRA_URL: ${ssm:JIRA_URL}
    JIRA_USERNAME: ${ssm:JIRA_USERNAME}
    JIRA_PASSWORD: ${ssm:JIRA_PASSWORD~true}

functions:
  sort-by-importance:
    handler: src/functions/sort-by-importance.handler
    events:
      - http: POST sort-by-importance
      - schedule: cron(5 12 * * ? *)
