service: jira-webhooks

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2

  environment:
    JIRA_URL: ${ssm:JIRA_URL}
    JIRA_USERNAME: ${ssm:JIRA_USERNAME}
    JIRA_PASSWORD: ${ssm:JIRA_PASSWORD~true}
    JIRA_BOARD_ID: ${ssm:JIRA_BOARD_ID}

functions:
  rank_issue_highest:
    handler: src/webhooks/rank-issue-highest.onTodo
    events:
      - http: POST rank_issue_highest

  auto_up_next:
    handler: src/webhooks/auto-up-next.onDone
    events:
      - http: POST auto_up_next

  sort_up_next:
    handler: src/webhooks/sort-up-next.handler
    events:
      - http: POST sort_up_next
      - http: POST sort_up_next_by_epic # backcompat

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp

#    Define function environment variables here
#    environment:
#      variable2: value2
